replicaCount: 1

image:
  repository: "ghcr.io/mooky0/ocr-backend"
  tag: "831d15c"

service:
  port: 8000

env:
  dbUrl: "postgresql://user:pass@postgres:5432/ocrdb"
  minioUrl: "minio:9000"
  minioRootUser: "admin"
  minioRootPassword: "password"