apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocr-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mooky0/ocr-webapp.git
    targetRevision: HEAD
    path: infra/charts/ocr-backend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true